apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fairgpu-eval-out-pvc
  namespace: systems-research-lab
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: rook-cephfs
  resources:
    requests:
      storage: 10Gi
